### Find all Content
GET http://localhost:8080/api/content


### Get Content by ID
GET http://localhost:8080/api/content/2


### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
    "id": 2,
    "title": "My Second blod Post",
    "desc" : "The second blog post",
    "status": "IDEA",
    "contentType": "COURSE",
    "dateCreated": "2023-02-13T10:25:02.838496",
    "dateUpdated": null,
    "url": ""

}


### Update new Content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
    "id": 1,
    "title": "MY FIRST POST",
    "desc" : "Updated Post",
    "status": "IDEA",
    "contentType": "COURSE",
    "dateCreated": "2023-02-13T10:25:02.838496",
    "dateUpdated": "2024-02-13T10:25:02.838496",
    "url": "http://localhost:8080/my-first-blog-post"

}
### Update existing Content with invalid ID
PUT http://localhost:8080/api/content/99
Content-Type: application/json

{
    "id": 1,
    "title": "MY FIRST POST",
    "desc" : "Updated Post",
    "status": "IDEA",
    "contentType": "COURSE",
    "dateCreated": "2023-02-13T10:25:02.838496",
    "dateUpdated": "2024-02-13T10:25:02.838496",
    "url": "http://localhost:8080/my-first-blog-post"

}